version: '3.8' # Más compatible y estable
services:
  db:
    image: postgres:13
    container_name: db_penjat
    environment:
      - POSTGRES_DB=penjat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5433:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_penjat
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2024_abdelaziz.kafi@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: AKAT2016
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
